name: sailiqwind
description: SailIQWind project
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_reactive_ble:
    git:
      url: https://github.com/PhilipsHue/flutter_reactive_ble.git
      path: packages/flutter_reactive_ble
      ref: master
  permission_handler: ^11.3.1
  flutter_riverpod: ^2.4.5
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.6

dependency_overrides:
  reactive_ble_platform_interface:
    git:
       url: https://github.com/PhilipsHue/flutter_reactive_ble.git
       path: packages/reactive_ble_platform_interface
       ref: master
  reactive_ble_mobile:
     git:
       url: https://github.com/PhilipsHue/flutter_reactive_ble.git
       path: packages/reactive_ble_mobile
       ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"